import React, { useState } from 'react';


const MedicalTermSimplifier = () => {
  const [inputText, setInputText] = useState('');
  const [simplifiedText, setSimplifiedText] = useState('');

  // Custom dictionary of medical terms and their simplified versions
  const medicalDictionary = {
    "myocardial infarction": "heart attack",
    "ECG": "heart test",
    "ST-segment elevation": "a problem with the heart's electrical activity",
    "hypertension": "high blood pressure",
    "diabetes mellitus": "diabetes",
    "gastroesophageal reflux disease": "acid reflux",
    "pneumonia": "lung infection",
    "aneurysm": "bulging blood vessel",
    "arthritis": "joint inflammation",
    "asthma": "airway inflammation",
    "bronchitis": "lung inflammation",
    "carcinoma": "cancerous tumor",
    "cirrhosis": "liver scarring",
    "cholecystitis": "gallbladder inflammation",
    "colitis": "colon inflammation",
    "conjunctivitis": "pink eye",
    "encephalitis": "brain inflammation",
    "gastritis": "stomach inflammation",
    "gingivitis": "gum inflammation",
    "hepatitis": "liver inflammation",
    "otitis media": "ear infection",
    "pancreatitis": "pancreas inflammation",
    "phlebitis": "vein inflammation",
    "sinusitis": "sinus inflammation",
    "tendonitis": "tendon inflammation",
    "tonsillitis": "tonsil inflammation",
    "appendicitis": "appendix inflammation",
    "diverticulitis": "diverticulum inflammation",
    "endocarditis": "heart lining inflammation",
    "meningitis": "brain lining inflammation",
    "peritonitis": "abdominal lining inflammation",
    "pleuritis": "pleura inflammation",
    "polyarthritis": "multiple joint inflammation",
    "thyroiditis": "thyroid inflammation",
    "cystitis": "bladder inflammation",
    "dermatitis": "skin inflammation",
    "enteritis": "intestinal inflammation",
    "esophagitis": "esophagus inflammation",
    "keratitis": "cornea inflammation",
    "myelitis": "spinal cord inflammation",
    "pericarditis": "heart sac inflammation",
    "polyneuritis": "multiple nerve inflammation",
    "radiculitis": "nerve root inflammation",
    "rhinitis": "nasal cavity inflammation",
    "uveitis": "eye inflammation",
    "anemia": "low red blood cells",
    "cancer": "abnormal cell growth",
    "emphysema": "loss of lung elasticity",
    "fibrosis": "scar tissue formation",
    "gallstones": "hardened bile deposits",
    "glaucoma": "increased eye pressure",
    "infection": "invading microorganisms",
    "jaundice": "yellowing of the skin",
    "leukemia": "blood cancer",
    "melanoma": "skin cancer",
    "obesity": "excessive body fat",
    "osteoporosis": "bone weakening",
    "psoriasis": "skin condition",
    "stroke": "brain blood vessel blockage",
    "ulcer": "stomach sore",
    "anxiety": "nervousness",
    "cataract": "clouding of the eye lens",
    "depression": "sadness",
    "incontinence": "loss of bladder control",
    "leukocytosis": "high white blood cells",
    "leukopenia": "low white blood cells",
    "lymphadenopathy": "swollen lymph nodes",
    "melena": "black stools",
    "menorrhagia": "heavy menstrual bleeding",
    "myalgia": "muscle pain",
    "nephrolithiasis": "kidney stones",
    "neutropenia": "low neutrophils",
    "oliguria": "low urine output",
    "orthopnea": "shortness of breath when lying down",
    "pallor": "paleness",
    "palpitations": "heart fluttering",
    "paresthesia": "tingling",
    "polyphagia": "excessive hunger",
    "polydipsia": "excessive thirst",
    "polyuria": "excessive urination",
    "pruritus": "itching",
    "pyrexia": "fever",
    "rhinorrhea": "runny nose",
    "tachycardia": "fast heartbeat",
    "tinnitus": "ringing in the ears",
    "urticaria": "hives",
    "vertigo": "dizziness",
    "xanthoma": "yellow skin growths",
    "xerostomia": "dry mouth",
    "adenitis": "gland inflammation",
    "adenoma": "gland tumor",
    "adenopathy": "gland disease",
    "angiitis": "vessel inflammation",
    "angioma": "vessel tumor",
    "arthropathy": "joint disease",
    "cardiomegaly": "enlarged heart",
    "cardiomyopathy": "heart muscle disease",
    "colposcopy": "cervix examination",
    "cystectomy": "bladder removal",
    "dysphasia": "difficulty speaking",
    "encephalopathy": "brain disease",
    "endometriosis": "uterine lining outside uterus",
    "epididymitis": "epididymis inflammation",
    "fibromyalgia": "muscle pain syndrome",
    "gastroenteritis": "stomach and intestine inflammation",
    "glomerulonephritis": "kidney inflammation",
    "hemorrhoids": "swollen rectal veins",
    "hypercholesterolemia": "high cholesterol",
    "hypertrophy": "enlargement",
    "hysterectomy": "uterus removal",
    "leukoplakia": "white patches",
    "lymphoma": "lymph node cancer",
    "myopathy": "muscle disease",
    "nephrectomy": "kidney removal",
    "neuropathy": "nerve disease",
    "oophorectomy": "ovary removal",
    "osteomyelitis": "bone inflammation",
    "otitis": "ear inflammation",
    "paralysis": "loss of movement",
    "pharyngitis": "throat inflammation",
    "pleurisy": "lung lining inflammation",
    "proctitis": "rectum inflammation",
    "pyelonephritis": "kidney infection",
    "retinopathy": "retina disease",
    "salpingitis": "fallopian tube inflammation",
    "scleroderma": "hard skin",
    "splenomegaly": "enlarged spleen",
    "thrombocytopenia": "low platelets",
    "thyroidectomy": "thyroid removal",
    "tracheitis": "windpipe inflammation",
    "urethritis": "urethra inflammation",
    "vasculitis": "blood vessel inflammation",
    "vulvitis": "vulva inflammation",
    "ankylosing spondylitis": "spinal arthritis",
    "cystic fibrosis": "mucus buildup in lungs",
    "epiglottitis": "epiglottis inflammation",
    "erythrocytosis": "high red blood cells",
    "hemochromatosis": "iron overload",
    "hyperparathyroidism": "overactive parathyroid",
    "hypoparathyroidism": "underactive parathyroid",
    "hypothyroidism": "underactive thyroid",
    "idiopathic thrombocytopenic purpura": "low platelets",
    "ischemic colitis": "colon blood flow reduction",
    "lupus erythematosus": "autoimmune disease",
    "myasthenia gravis": "muscle weakness",
    "polymyositis": "muscle inflammation",
    "Raynaud's disease": "poor blood flow",
    "Sjogren's syndrome": "dry mouth and eyes",
    "systemic lupus erythematosus": "autoimmune disease",
    "thrombophlebitis": "vein inflammation with clot",
    "Wegener's granulomatosis": "blood vessel inflammation",
    "allergic rhinitis": "hay fever",
    "alopecia areata": "hair loss",
    "amyloidosis": "protein buildup",
    "asbestosis": "lung disease from asbestos",
    "atopic dermatitis": "eczema",
    "biliary cirrhosis": "bile duct inflammation",
    "chronic fatigue syndrome": "extreme tiredness",
    "Crohn's disease": "intestinal inflammation",
    "eosinophilic esophagitis": "allergic esophagus inflammation",
    "granulomatosis with polyangiitis": "blood vessel inflammation",
    "Hashimoto's thyroiditis": "thyroid inflammation",
    "liver cirrhosis": "liver scarring",
    "Ménière's disease": "inner ear disorder",
    "necrotizing fasciitis": "flesh-eating disease",
    "psoriatic arthritis": "arthritis with psoriasis",
    "Reiter's syndrome": "reactive arthritis",
    "urticaria pigmentosa": "skin mast cell buildup",
    "Whipple's disease": "bacterial infection",
    "achalasia": "esophagus disorder",
    "adrenocortical carcinoma": "adrenal cancer",
    "alpha-1 antitrypsin deficiency": "genetic disorder",
    "Barrett's esophagus": "esophagus damage",
    "Charcot-Marie-Tooth disease": "nerve damage",
    "Chédiak-Higashi syndrome": "immune system disorder",
    "Crigler-Najjar syndrome": "bilirubin buildup",
    "Cushing's syndrome": "high cortisol levels",
    "Duchenne muscular dystrophy": "muscle degeneration",
    "Ehlers-Danlos syndrome": "connective tissue disorder",
    "Fanconi anemia": "blood disorder",
    "Gaucher disease": "lipid storage disorder",
    "Goodpasture syndrome": "lung and kidney disease",
    "Graves' disease": "overactive thyroid",
    "Guillain-Barré syndrome": "nerve inflammation",
    "Hirschsprung's disease": "colon disorder",
    "Huntington's disease": "brain disorder",
    "Klinefelter syndrome": "genetic disorder",
    "Lambert-Eaton syndrome": "muscle weakness",
    "Lesch-Nyhan syndrome": "genetic disorder",
    "Marfan syndrome": "connective tissue disorder",
    "Morquio syndrome": "skeletal disorder",
    "Neurofibromatosis": "tumors on nerves",
    "Niemann-Pick disease": "lipid storage disorder",
    "Patau syndrome": "genetic disorder",
    "Prader-Willi syndrome": "genetic disorder",
    "Rett syndrome": "genetic disorder",
    "Shwachman-Diamond syndrome": "bone marrow disorder",
    "Sjögren's syndrome": "dry mouth and eyes",
    "Spinal muscular atrophy": "muscle wasting",
    "Sturge-Weber syndrome": "brain and skin disorder",
    "Tay-Sachs disease": "genetic disorder",
    "Treacher Collins syndrome": "genetic disorder",
    "Trisomy 13": "genetic disorder",
    "Trisomy 18": "genetic disorder",
    "Turner syndrome": "genetic disorder",
    "von Hippel-Lindau disease": "tumors in various organs",
    "Williams syndrome": "genetic disorder",
    "Wilson's disease": "copper buildup",
    "Xeroderma pigmentosum": "skin disorder",
    "Zellweger syndrome": "genetic disorder",
    'acute dyspnea': 'sudden difficulty breathing',
  
  'cyanosis': 'bluish skin',
  'pulmonary embolism': 'blood clot in the lung',
  'bilateral crepitus': 'crackling sounds in both sides of the chest',
  'pneumothorax': 'collapsed lung',
  'chest X-ray': 'chest imaging',
  'arterial blood gas analysis': 'blood test for oxygen and carbon dioxide levels',
  'differential diagnoses': 'possible alternative diagnoses',
  
  
  'acute respiratory distress syndrome': 'severe lung failure',
  'supplemental oxygen therapy': 'extra oxygen',
  'anticoagulants': 'blood thinners',
  'vital signs': 'key health indicators',
  'heart rate': 'pulse',
  'blood pressure': 'force of blood against arteries',
  'oxygen saturation': 'blood oxygen level',
  'hemodynamic stability': 'stable blood circulation',
  'anaphylaxis': "severe allergic reaction",
  "angina": "chest pain",
  "arrhythmia": "irregular heartbeat",
  "atherosclerosis": "hardening of the arteries",
  "benign": "non-cancerous",
  "biopsy": "tissue sample",
  "bursitis": "joint inflammation",
  "carpal tunnel syndrome": "wrist nerve compression",
  "cellulitis": "skin infection",
  "cholesterol": "blood fat",
  "chronic": "long-lasting",
  "congestive heart failure": "heart failure",
  "contusion": "bruise",
  "coronary artery disease": "heart artery blockage",
  "debridement": "wound cleaning",
  "dementia": "memory loss",
  "diagnosis": "identification of a disease",
  "dysphagia": "difficulty swallowing",
  "edema": "swelling",
  "electrocardiogram": "heart test",
  
  "endometritis": "uterine inflammation",
  "epilepsy": "seizure disorder",
  "erythema": "skin redness",
  "febrile": "having a fever",
  "gastroenterologist": "digestive system doctor",
  "gastroscopy": "stomach examination",
  "gout": "joint pain from uric acid crystals",
  "hematoma": "blood clot",
  "hematuria": "blood in urine",
  "hemorrhage": "bleeding",
  "hypoglycemia": "low blood sugar",
  "hypotension": "low blood pressure",
  "hypothermia": "low body temperature",
  "infarction": "tissue death",
  "insomnia": "sleeplessness",
  "intravenous": "through a vein",
  "laceration": "deep cut",
  "malignant": "cancerous",
  "mastectomy": "breast removal",
  
  "metastasis": "spread of cancer",
  "migraine": "severe headache",
  "myocarditis": "heart muscle inflammation",
  "neonatal": "related to newborns",
  "neonatology": "study of newborns",
  "neurologist": "brain and nerve doctor",
  "neurology": "study of the nervous system",
  "nodule": "small growth",
  "oncologist": "cancer doctor",
  "oncology": "study of cancer",
  "ophthalmologist": "eye doctor",
  "ophthalmology": "study of the eyes",
  "orthodontist": "teeth alignment doctor",
  "orthopedic": "musculoskeletal system",
  "orthopedist": "bone and joint doctor",
  "palliative care": "comfort care",
  "paraplegia": "lower body paralysis",
  "pulmonologist": "lung doctor",
  "pulmonology": "study of the lungs",
  "rheumatologist": "joint and autoimmune disease doctor",
  "rheumatology": "study of joint and autoimmune diseases",
  "sedation": "calming medication",
  "surgery": "operation",
  "thrombosis": "blood clot",
  "ultrasound": "sonogram",
  "urologist": "urinary system doctor",
  "urology": "study of the urinary system",
  "vaccination": "immunization",
  "vaccine": "immunization",
  "varicose veins": "swollen veins",
  "vasectomy": "male sterilization",
  "vasoconstriction": "blood vessel narrowing",
  "vasodilation": "blood vessel widening",
  "virus": "infectious agent",
  "x-ray": "radiograph"

    // Add more terms as needed
  };

  // Function to simplify medical terms in text
  const simplifyMedicalTerms = (text) => {
    let simplifiedText = text;

    Object.keys(medicalDictionary).forEach((term) => {
      const regex = new RegExp(`\\b${term}\\b`, 'gi');
      simplifiedText = simplifiedText.replace(regex, medicalDictionary[term]);
    });

    return simplifiedText;
  };

  // Handler function for simplifying text
  const handleSimplifyText = () => {
    const simplified = simplifyMedicalTerms(inputText);
    setSimplifiedText(simplified);
  };

  return (
    <div>
      <textarea
        value={inputText}
        onChange={(e) => setInputText(e.target.value)}
        placeholder="Enter text containing medical terms..."
      />
      <button onClick={handleSimplifyText}>Simplify Text</button>
      <div>
        <h2>Simplified Text:</h2>
        <p>{simplifiedText}</p>
      </div>
    </div>
  );
};

export default MedicalTermSimplifier;
